@startuml
note bottom of csvReader: read the csv and write to the database
abstract class csvReader{
    # infoSourceId : int
    # firmId : int
    # fileResource : resource
    # headerLine : int
    # colTitle : array
    # csvArray : array
    # _csvStructure : array
    # _csvArray : array
    # __construct(filePath : string)
    + {static} process():bool
    # processing():bool
    # readCsv():bool
    # str2Arr():array
    # writeToDatabase():bool
}



note bottom of csvReaderBaidu: <b>colTitle:</b> convert csv filed into database field\n<b>headerLine: </b>Indicate which line is the header of the csv file
class csvReaderBaidu {
    ..rewrite..
    # headerLine : int
    # colTitle : array
    + __construct()
}

csvReader <|-csvReaderBaidu : < extends
@enduml
